schema-version: v1
kind: plugin
metadata:
  name: porto-robot-plugin
  display-name: porto-robot-plugin
  description: Criar estrutura de arquivos de teste Porto Robot
  version: 0.0.2
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  technologies:
    - Android
  inputs:
    - label: Enter the package name
      name: package_name
      type: text
      default: "br.com.portoseguro"

    - label: Enter the module name
      name: module_name
      type: text
      required: true
      help: 'Inform module name. Eg: vehicledebt'

    - label: Enter the feature name
      name: feature_name
      type: text
      required: true
      help: 'Inform the feature name beign tested. eg: debtlist'

    - label: Choose Activity or Fragment
      name: choose_type
      type: text
      items:
        - Activity
        - Fragment
      required: true
      help: 'Inform the type of the test class'

    - label: Enter the full class name
      name: class_name
      type: text
      required: true
      help: 'Inform the name of the class. eg: VehicleDebtsFragment'

  computed-inputs:
    choose_type_lower: "{{choose_type|lower}}"
    feature_name_lower: "{{feature_name|lower}}"
    full_package_path: "{{package_name|replace('.', '/')}}/{{module_name|replace('.', '/')}}"