schema-version: v1
kind: plugin
metadata:
  name: porto-robot-plugin
  display-name: porto-robot-plugin
  description: Criar estrutura de arquivos de teste Porto Robot
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - Api
  inputs:
    - label: Choose Activity or Fragment
      name: choose_type
      type: text
      items:
        - Activity
        - Fragment
      default: Activity
      required: true
      help: 'Inform the type of the test class'
    - label: Activity or Fragment name
      name: enter_name
      type: text
      required: true
      help: 'Inform the name of the class'